### ISSUE TITLE
In Daily Servings History graph, Servings bars ignore missed days but Moving Average does not.

### ISSUE THREAD

**Issue by StuRMiller** [nutritionfactsorg/daily-dozen-android#122]
![image](https://user-images.githubusercontent.com/54312691/63339954-e857cb80-c33d-11e9-818b-809a92cf00f8.png)

**Overview of the Issue** - In the Daily Servings History graph, the bar chart for servings excludes days which have no check boxes ticked (in example above, dates from 7th Aug - 13th Aug are not filled in). The moving average is adjusted to include missed days. In the picture example, the moving average dips to 9.48 after a period of 0 serving days despite the displayed serving bars always being higher than that (to the left of this point, the lowest servings count is 12). 

I would have expected the moving average to use the same base dataset as the servings bars. It seems potentially misleading to change whether missed days are considered significant or not on the same graph, especially if we're assuming these days are simply not filled in by the user, rather than them truly having 0 servings.

These missing days are intentionally being added into the moving average: this calculation exits in LoadServingsHistoryTask.java, line 92. I'd be interested to read the reason is behind this.

**Android Version(s)** - 8.0.0
**Device Model** - Samsung Galaxy A3
**Daily Dozen App Version** - 15.1

**Comment by danuker** [comment]
Here is the commit introducing the adjustment (I found it using the "Blame" feature of Git / GitHub):
https://github.com/nutritionfactsorg/daily-dozen-android/pull/48/commits/05eb96e9b962b6d3be649f5f933ebe7486a98bf5

It assumes you have not served any food, if you have not ticked their boxes. I think this is the correct behavior. You can always go back and tick them if you remember.

As for the bars, I think it's fine to see just the days when you have checked anything. While it is inconsistent, here's my 2 cents:

Displaying a row of empty bars on a limited-width device is pointless - especially since you have the dates correctly marked above the bars. I don't want to side-scroll empty bars.

**Comment by slavick** [comment]
Thanks for finding this bug, this was indeed unintended behavior. This issue has been fixed and days with 0 servings will be shown in the graph. I like this behavior because if multiple days are skipped, the user can see their moving average decrease with each missed day.
