### ISSUE TITLE
Is this project still active?

### ISSUE THREAD

**Issue by andrewjrangel** [nutritionfactsorg/daily-dozen-android#151]
I see that there are a lot of Pull Requests that are older and it has been awhile since a release. Is this still being supported?

**Comment by marc-medley** [comment]
@andrewjrangel , Daily Dozen Android has been, and is an ongoing project.

Please notice that the majority of Daily Dozen Android pull requests are related to language translations. The pull requests would add 5 languages to the existing 11 languages already present in the Android version.

On the other hand, Daily Dozen iOS _has not had any multi-language localization support_ until very recently.

So, the recent months since that Feb 3, 2020 v17.1 Android release has been a catchup time for iOS to have the infrastructure to be able to accept addition languages.

Since, your particular focus appears to be Swift programming, you would be welcome to build/test/use the recent [Daily Dozen iOS version](https://github.com/nutritionfactsorg/daily-dozen-ios) multi-language capable version and provide feedback.
