### ISSUE TITLE
Wrong information about grams?

### ISSUE THREAD

**Issue by eminem0091** [nutritionfactsorg/daily-dozen-android#193]
Hello,

Maybe I do not understand but....

https://github.com/nutritionfactsorg/daily-dozen-android/blob/master/app/src/main/res/values/strings.xml#L714-L727

In app
1 cup raw = 60 g
½ cup cooked = 90 g

Or this is correct?
½ cup raw = 60 g
1 cup cooked = 90 g

Thanks :)

**Comment by slavick** [comment]
It could be a mistake, but my version of How Not to Die only has Imperial units. Do you have any suggested values?

**Comment by eminem0091** [comment]
no :/

**Comment by marc-medley** [comment]
@eminem0091 Is your underlaying question with (1) code accuracy, (2) raw vs. cooked density or (3) a specific value for the broad (and approximate) guideline for greens?

Please see if the notes below address your concerns.

First, what is in the xml source code is provided in array order ...

``` xml
 <string-array name="food_info_serving_sizes_greens">
        <item>%s raw</item>
        <item>%s cooked</item>
    </string-array>

    <string-array name="food_info_serving_sizes_greens_imperial">
        <item>1 cup</item>
        <item>½ cup</item>
    </string-array>

    <string-array name="food_info_serving_sizes_greens_metric">
        <item>60 g</item>
        <item>90 g</item>
    </string-array>
```

and does accurately correspond to the following in the app:

```
1 cup raw = 60 g
½ cup cooked = 90 g
```

Second, raw leafy greens are not a dense (grams/liter) and cooked greens. So, yes, a smaller volume of cooked greens can weight more than the cook greens.

Third, the quantity provides a general approximate guideline. For example, the weight can vary by how tightly the raw greens are packed, or by how well drained boiled greens are drained.

With Spinach as an example, based on one nutritional database, one can find

_Spinach, cooked, boiled, drained_ is **90 g per ½ cup**
--> https://nutritiondata.self.com/facts/vegetables-and-vegetable-products/2627/2

And _Spinach, raw_ is reported at **30 g per 1 cup** (likely unpacked since cutting and packing can weight more per cup).
https://nutritiondata.self.com/facts/vegetables-and-vegetable-products/2626/2

**Comment by eminem0091** [comment]
ahh... thank you guys :) now I fully understand :)
