### ISSUE TITLE
Kale listed in two categories

### ISSUE THREAD

**Issue by Ainali** [nutritionfactsorg/daily-dozen-android#259]
Kale is listed under both Cruciferous Vegetables and under Greens. Is that intended or just a bug?

Steps to Reproduce the Issue: Press the info for each of those categories and see it listed under Types in both. 

- Daily Dozen App Version: 27

**Comment by slavick** [comment]
It is correct, kale is both a dark green leafy vegetable and a cruciferous vegetable. A serving of kale can count as either, but one serving is one serving. In order to mark off a greens serving and a cruciferous serving you'd have to eat one kale serving of each according to the respective serving sizes.
