### ISSUE TITLE
Add and Update Chinese Translation

### ISSUE THREAD

**Issue by christirichards** [nutritionfactsorg/daily-dozen-android#67]
I have a copy of a contributed translation, but it is behind on a few strings recently added to the app.  It would be helpful if someone could fill in the gaps with what is missing and go ahead and add it to the project.

[Download values-zh on Dropbox](https://www.dropbox.com/s/zzqs5794rpeyiq7/values-zh.zip)

**Comment by ikyli** [comment]
[values-zh.zip](https://github.com/nutritionfactsorg/daily-dozen-android/files/1368259/values-zh.zip)

**Comment by alibitek** [comment]
@ikyli 
I've looked at your strings.xml file and there are some issues:
- The items in following string arrays shouldn't be translated, because there is no string defined with the "name" translated: food_names, notification_icon_food_names . 
The items in the array are just referencing string definitions from above.
- Besides those changes I cannot see anything else you've done: http://mergely.com/CWETFSW1/
The changes you've made are not necessary and we need to clarify exactly what are strings needed to be updated in the file.

@christirichards Can you please specify the string names for which there is a need of an updated Chinese translation?
So that people interested in contributing can know what they have to translate.

**Comment by slavick** [comment]
This issue is outdated at this point. I am closing this now as the Chinese translation has been added to the app.
